### ISSUE TITLE
fail to install dependency in requirements.txt

### ISSUE THREAD

**Issue by pangzineng** [alvations/cliffjumper#1]
`torch==1.3.0` could not be installed via pip

**Comment by alvations** [comment]
Try this:

```
python -m pip install -U pip
python -m pip install -U torch==1.3.0
```

**Comment by pangzineng** [comment]
> 
> 
> Try this:
> 
> ```
> python -m pip install -U pip
> python -m pip install -U torch==1.3.0
> ```

```
root@07536a20db7b:/app# python -m pip install -U pip
Requirement already up-to-date: pip in /usr/local/lib/python3.8/site-packages (19.3.1)
root@07536a20db7b:/app# python -m pip install -U torch==1.3.0
ERROR: Could not find a version that satisfies the requirement torch==1.3.0 (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch==1.3.0
```

This is a docker container of official `python:3` image, your enviornment might have other stuff installed or some kind of custom configuration?

**Comment by pangzineng** [comment]
the `torch` dependency could be installed if I switch to a conda image `continuumio/miniconda3`

the `nmslib` dependency could not be installed directly on Alpine Linux based docker image (which is basically most of the offical images), the following libraries need to be installed (apt-get / apk) first: 
* gcc
* linux-libc-dev
* libc-dev

**Comment by alvations** [comment]
Ah yes, it's actually "not python" but more C++ library. Python is just the wrapper. 

It's best to start with ubuntu base image?
